"""init

Revision ID: 1ac9f1a295f0
Revises: 
Create Date: 2023-10-16 19:49:16.546535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac9f1a295f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_id'), ['id'], unique=False)

    op.create_table('customer_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('geolocation', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'customer_id', name='unique_address_customer_id')
    )
    with op.batch_alter_table('customer_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_address_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_address_id'))

    op.drop_table('customer_address')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_id'))

    op.drop_table('customer')
    # ### end Alembic commands ###
